name: rcspos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.4
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  getwidget: ^6.0.0
  path_provider: ^2.1.2
  razorpay_flutter: ^1.4.0
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.10.2
  flutter_razorpay_web: ^0.0.3
  webview_windows: ^0.4.0
  mobile_scanner: ^7.0.1
  workmanager: ^0.8.0
  flutter_inappwebview: ^6.0.0
  csv: ^5.0.2
  pdf: ^3.10.4 # Use the latest version available
  printing: ^5.12.0 
  excel: ^2.1.0
  file_saver: ^0.3.1	
  permission_handler: ^11.0.0
  barcode_scanner: ^7.0.0
  http: ^1.4.0
  url_launcher: ^6.3.2
  fluttertoast: ^8.2.10
  ffi: ^2.1.0
  intl: ^0.20.2
  sqlite3: ^2.7.6
  syncfusion_flutter_xlsio: ^25.1.39
  dotted_line: ^3.1.0 
  file_picker: ^8.0.0
  lottie: ^2.7.0
  flutter_localizations:
    sdk: flutter
  paged_datatable: ^2.0.0
  awesome_snackbar_content: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.2
  sqlite3_flutter_libs: ^0.5.34

flutter:
  uses-material-design: true
  assets:
    - assets/razorpay_checkout.html
    - assets/rcslogo.png
    - assets/paymentsuccesslogo.gif
    - assets/bgimage2.webp
    
  fonts:
    - family: Arial