name: rcspos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.4
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  razorpay_flutter: ^1.4.0
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.10.2
  flutter_razorpay_web: ^0.0.3
  webview_windows: ^0.4.0
  http: ^1.4.0
  url_launcher: ^6.3.2
  fluttertoast: ^8.2.10
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  paged_datatable: ^2.0.0
  awesome_snackbar_content: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/razorpay_checkout.html
