// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
            case TargetPlatform.linux:
        return linux;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDrIvndmdDlX4AtnWbDLmr19wjwO9wpI',
    appId: '1:562355947875:web:3786e9cd84cfb63f4e2b56',
    messagingSenderId: '562355947875',
    projectId: 'rcs-pos-14fff',
    authDomain: 'rcs-pos-14fff.firebaseapp.com',
    storageBucket: 'rcs-pos-14fff.firebasestorage.app',
    measurementId: 'G-E0VVW4DZ02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYWhJGWSKF40o4Yq1o2bqtRiHihvXPStA',
    appId: '1:562355947875:android:a90e60465ff4a0a14e2b56',
    messagingSenderId: '562355947875',
    projectId: 'rcs-pos-14fff',
    storageBucket: 'rcs-pos-14fff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyColqhy6WgRrLUiIFoNnMTYTowJJKNbUGw',
    appId: '1:562355947875:ios:b532ae5f4f904a944e2b56',
    messagingSenderId: '562355947875',
    projectId: 'rcs-pos-14fff',
    storageBucket: 'rcs-pos-14fff.firebasestorage.app',
    iosBundleId: 'com.example.rcspos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyColqhy6WgRrLUiIFoNnMTYTowJJKNbUGw',
    appId: '1:562355947875:ios:b532ae5f4f904a944e2b56',
    messagingSenderId: '562355947875',
    projectId: 'rcs-pos-14fff',
    storageBucket: 'rcs-pos-14fff.firebasestorage.app',
    iosBundleId: 'com.example.rcspos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPDrIvndmdDlX4AtnWbDLmr19wjwO9wpI',
    appId: '1:562355947875:web:a201d6cbfea9f01f4e2b56',
    messagingSenderId: '562355947875',
    projectId: 'rcs-pos-14fff',
    authDomain: 'rcs-pos-14fff.firebaseapp.com',
    storageBucket: 'rcs-pos-14fff.firebasestorage.app',
    measurementId: 'G-FLG0GWC8CM',
  );

    static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDPDrIvndmdDlX4AtnWbDLmr19wjwO9wpI',
    appId: '1:562355947875:web:a201d6cbfea9f01f4e2b56',
    messagingSenderId: '562355947875',
    projectId: 'rcs-pos-14fff',
    authDomain: 'rcs-pos-14fff.firebaseapp.com',
    storageBucket: 'rcs-pos-14fff.appspot.com',
    measurementId: 'G-FLG0GWC8CM',
  );


}